In [ ]:
import numpy as np
import pandas as pd

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

## 데이터 셋: 타이타닉 데이터셋 (출처: Kaggle.com)

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

* PassengerId: 승객 아이디
* Survived: 생존 여부, 1: 생존, 0: 사망
* Pclass: 등급
* Name: 성함
* Sex: 성별
* Age: 나이
* SibSp: 형제, 자매, 배우자 수
* Parch: 부모, 자식 수
* Ticket: 티켓번호
* Fare: 요금
* Cabin: 좌석번호
* Embarked: 탑승 항구

## 전처리: train / validation 세트 나누기

1. 먼저, feature 와 label을 정의합니다.
2. feature / label을 정의했으면, 적절한 비율로 train / validation set을 나눕니다.

In [ ]:
feature = [
           'Pclass', 'Sex', 'Age', 'Fare'    
]

In [ ]:
label = [
         'Survived'
]

In [ ]:
train[feature].head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [ ]:
train[label].head()

Survived
0         0
1         1
2         1
3         1
4         0

In [ ]:
from sklearn.model_selection import train_test_split

* **test_size**: validation set에 할당할 비율 (20% -> 0.2)
* **shuffle**: 셔플 옵션 (기본 True)
* **random_state**: 랜덤 시드값

# **return받는 데이터의 순서가 중요하다.!!!!!!!!!!!!!!!!!!!!!!!!**

In [ ]:
x, x_val, y, y_val = train_test_split(train[feature], train[label], test_size=0.2, shuffle=True, random_state=30)

In [ ]:
x.shape, y.shape

((712, 4), (712, 1))

In [ ]:
x_val.shape, y_val.shape

((179, 4), (179, 1))

## 전처리: 결측치

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


결측치를 확인하는 방법은 pandas의 **isnull()** 

그리고 합계를 구하는 sum()을 통해 한 눈에 확인할 수 있습니다.

In [ ]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

개별 column의 결측치에 대하여 확인하는 방법은 다음과 같습니다.

In [ ]:
train['Age'].isnull().sum()

177

Impute 도큐먼트(https://scikit-learn.org/stable/modules/impute.html)

### 1. 수치형 (Numerical Column) 데이터에 대한 결측치 처리

In [ ]:
train['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [ ]:
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [ ]:
train['Age'].fillna(train['Age'].mean()).describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

imputer: 2개 이상의 column을 한 번에 처리할 때

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
impute = SimpleImputer(strategy='mean')

fit() 을 통해 결측치에 대한 학습을 진행합니다.

In [ ]:
impute.fit(train[['Age']])

SimpleImputer()

transform() 은 실제 결측치에 대한 처리를 해주는 함수합니다.

In [ ]:
result = impute.transform(train[['Age']])

In [ ]:
result

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [ ]:
train[['Age']] = result

In [ ]:
train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [ ]:
train[['Age', 'Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.361582    2.308642
std     13.019697    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     28.000000    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

fit_transform()은 fit()과 transform()을 한 번에 해주는 함수 입니다.

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train[['Age', 'Pclass']].isnull().sum()

Age       177
Pclass      0
dtype: int64

In [ ]:
impute = SimpleImputer(strategy='median')

In [ ]:
result = impute.fit_transform(train[['Age']])

In [ ]:
train[['Age']] = result

In [ ]:
train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [ ]:
train[['Age', 'Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.361582    2.308642
std     13.019697    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     28.000000    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

### 2.  (Categorical Column) 데이터에 대한 결측치 처리

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

1개의 column을 처리하는 경우

In [ ]:
train['Embarked'].fillna('S')

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

Imputer를 사용하는 경우 : 2개 이상의 column을 처리할 때

In [ ]:
imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
result = imputer.fit_transform(train[['Embarked', 'Cabin']])

In [ ]:
train[['Embarked', 'Cabin']] = result

In [ ]:
train[['Embarked', 'Cabin']].isnull().sum()

Embarked    0
Cabin       0
dtype: int64

## Label Encoding : 문자(categorical)를 수치(numerical)로 변환

학습을 위해서 모든 문자로된 **데이터는 수치로 변환**하여야 합니다.

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
def convert(data):
  if data == 'male':
    return 1
  elif data == 'female':
    return 0

In [ ]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
train['Sex'].apply(convert)

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
train['Sex_num'] = le.fit_transform(train['Sex'])

In [ ]:
train['Sex_num'].value_counts()

1    577
0    314
Name: Sex_num, dtype: int64

In [ ]:
le.classes_

array(['female', 'male'], dtype=object)

In [ ]:
le.inverse_transform([0,1,1,0,0,1,1])

array(['female', 'male', 'male', 'female', 'female', 'male', 'male'],
      dtype=object)

NaN 값이 포함되어 있다면, `LabelEncoder`가 정상 동작하지 않습니다.

In [ ]:
train['Embarked'] = train['Embarked'].fillna('S')

In [ ]:
le.fit_transform(train['Embarked'])

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1,

## 원 핫 인코딩 (One Hot Encoding)

In [ ]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [ ]:
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

`Embarked`를 살펴봅시다

In [ ]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
train['Embarked'] = train['Embarked'].fillna('S')

In [ ]:
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
train['Embarked_num'] = LabelEncoder().fit_transform(train['Embarked'])

In [ ]:
train['Embarked_num'].value_counts()

2    646
0    168
1     77
Name: Embarked_num, dtype: int64

Embarked는 탑승 항구의 이니셜을 나타냈습니다. 

그런데, 우리는 이전에 배운 내용처럼 `LabelEncoder`를 통해서 수치형으로 변환해주었습니다.

하지만, 이대로 데이터를 기계학습을 시키면, 기계는 데이터 안에서 관계를 학습합니다.

즉, 'S' = 2, 'Q' = 1 이라고 되어 있는데, `Q` + `Q` = `S` 가 된다 라고 학습해버린다는 것이죠.

그렇기 때문에, 독립적인 데이터는 별도의 column으로 분리하고,
각각의 컬럼에 해당 값에만 **True** 나머지는 **False**를 갖습니다.
우리는 이것은 원 핫 인코딩 한다라고 합니다.

In [ ]:
train['Embarked'][:11]

0     S
1     C
2     S
3     S
4     S
5     Q
6     S
7     S
8     S
9     C
10    S
Name: Embarked, dtype: object

In [ ]:
train['Embarked_num'][:11]

0     2
1     0
2     2
3     2
4     2
5     1
6     2
7     2
8     2
9     0
10    2
Name: Embarked_num, dtype: int64

In [ ]:
pd.get_dummies(train['Embarked_num'][:11])

0  1  2
0   0  0  1
1   1  0  0
2   0  0  1
3   0  0  1
4   0  0  1
5   0  1  0
6   0  0  1
7   0  0  1
8   0  0  1
9   1  0  0
10  0  0  1

In [ ]:
one_hot = pd.get_dummies(train['Embarked_num'][:11])

In [ ]:
one_hot

0  1  2
0   0  0  1
1   1  0  0
2   0  0  1
3   0  0  1
4   0  0  1
5   0  1  0
6   0  0  1
7   0  0  1
8   0  0  1
9   1  0  0
10  0  0  1

In [ ]:
one_hot.columns = ['C','Q','S']

In [ ]:
one_hot

C  Q  S
0   0  0  1
1   1  0  0
2   0  0  1
3   0  0  1
4   0  0  1
5   0  1  0
6   0  0  1
7   0  0  1
8   0  0  1
9   1  0  0
10  0  0  1

위와 같이 column 을 분리시켜 **카테고리형 -> 수치형으로 변환**하면서 생기는 `수치형 값`의 관계를 끊어주어서 독립적인 형태로 바꾸어 줍니다.

**원핫인코딩**은 카테고리 (계절, 항구, 성별, 종류, 한식/일식/중식...)의 특성을 가지는 column에 대해서 적용 합니다.

## 전처리: Normalize (정규화)

column 간에 다른 **min**, **max** 값을 가지는 경우, 정규화를 통해 최소치/ 최대값의 척도를 맞추어 주는 것

* 네이버 영화평점 (0점 ~ 10점): [2, 4, 6, 8, 10]
* 넷플릭스 영화평점 (0점 ~ 5점): [1, 2, 3, 4, 5]

In [ ]:
movie = {'naver' : [2, 4, 6, 8, 10],
         'netflix' : [1, 2, 3, 4, 5]
}

In [ ]:
movie = pd.DataFrame(data=movie)
movie

naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mms = MinMaxScaler()

In [ ]:
movie_normal = mms.fit_transform(movie)

In [ ]:
movie_normal

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [ ]:
pd.DataFrame(movie_normal, columns=['naver', 'netfliex'])

naver  netfliex
0   0.00      0.00
1   0.25      0.25
2   0.50      0.50
3   0.75      0.75
4   1.00      1.00

## 표준화 (Standard Scaling)

**평균이 0과 표준편차가 1**이 되도록 변환

In [164]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

샘플데이터를 생성합니다.

In [165]:
import numpy as np 

x = np.arange(10)
# outlier 추가
x[9] = 1000

In [166]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [167]:
scaled = standard_scaler.fit_transform(x.reshape(-1, 1))

In [ ]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [168]:
scaled.mean(), scaled.std()

(4.4408920985006264e-17, 1.0)

In [169]:
round(scaled.mean(),2), scaled.std()

(0.0, 1.0)

In [171]:
x

array([   0,    1,    2,    3,    4,    5,    6,    7,    8, 1000])

In [170]:
scaled

array([[-0.34670856],
       [-0.34336196],
       [-0.34001535],
       [-0.33666874],
       [-0.33332213],
       [-0.32997553],
       [-0.32662892],
       [-0.32328231],
       [-0.3199357 ],
       [ 2.9998992 ]])